Repository napframework/nap, pull requests merged in 2025-02, with the labels that each got.

#64 Smoothdamp fix
  system_modules/napmath/src/mathutils.cpp
  system_modules/napmath/src/mathutils.h
  system_modules/napmath/src/smoothdamp.cpp
  system_modules/napmath/src/smoothdamp.h
Labels: bug, enhancement

#79 fix for not hot reloading when editing files in sub directories of the data folder on linux
  core/src/nap/linux/FileWatcher/FileWatcherLinux.cpp
  core/src/nap/linux/FileWatcher/FileWatcherLinux.h
  core/src/nap/resourcemanager.cpp
Labels: bug, core

#83 Internal Textures, Links & Cleanup
  demos/audiovisualfft/data/objects.json
  demos/audiovisualfft/module/src/renderdofcomponent.cpp
  demos/computeflocking/data/computeflocking.json
  demos/videomodulation/data/videomodulation.json
  system_modules/napimgui/src/imguiicon.cpp
  system_modules/naprender/src/depthrendertarget.cpp
  system_modules/naprender/src/depthrendertarget.h
  system_modules/naprender/src/imagefromfile.cpp
  system_modules/naprender/src/imagefromfile.h
  system_modules/naprender/src/irendertarget.h
  system_modules/naprender/src/renderableglyph.cpp
  system_modules/naprender/src/renderbloomcomponent.cpp
  system_modules/naprender/src/renderservice.cpp
  system_modules/naprender/src/renderservice.h
  system_modules/naprender/src/rendertarget.cpp
  system_modules/naprender/src/rendertarget.h
  system_modules/naprender/src/rendertexture2d.cpp
  system_modules/naprender/src/rendertexture2d.h
  system_modules/naprender/src/rendertexturecube.cpp
  system_modules/naprender/src/rendertexturecube.h
  system_modules/naprender/src/renderwindow.h
  system_modules/naprender/src/snapshot.cpp
  system_modules/naprender/src/snapshotrendertarget.cpp
  system_modules/naprender/src/snapshotrendertarget.h
  system_modules/naprender/src/texture.cpp
  system_modules/naprender/src/texture.h
  system_modules/naprender/src/texturelink.h
  system_modules/naprender/src/textureutils.cpp
  system_modules/naprender/src/textureutils.h
  system_modules/naprenderadvanced/src/cubedepthrendertarget.h
  system_modules/naprenderadvanced/src/cubemapfromfile.cpp
  system_modules/naprenderadvanced/src/cubemapfromfile.h
  system_modules/naprenderadvanced/src/cuberendertarget.cpp
  system_modules/naprenderadvanced/src/cuberendertarget.h
  system_modules/naprenderadvanced/src/renderadvancedservice.cpp
  system_modules/napvideo/src/videoplayer.cpp
Labels: rendering

#67 Flexible buffer bindings
  core/src/nap/linux/FileWatcher/FileWatcherLinux.cpp
  core/src/nap/linux/FileWatcher/FileWatcherLinux.h
  core/src/nap/resourcemanager.cpp
  demos/audiovisualfft/app.json
  demos/audiovisualfft/build.sh
  demos/audiovisualfft/data/objects.json
  demos/audiovisualfft/module/src/renderdofcomponent.cpp
  demos/computeflocking/data/computeflocking.json
  demos/videomodulation/data/videomodulation.json
  system_modules/napaudio/module.json
  system_modules/napfft/module.json
  system_modules/napimgui/src/imguiicon.cpp
  system_modules/napmath/src/mathutils.cpp
  system_modules/napmath/src/mathutils.h
  system_modules/napmath/src/smoothdamp.cpp
  system_modules/napmath/src/smoothdamp.h
  system_modules/napportaudio/module.json
  system_modules/naprender/src/bufferbinding.h
  system_modules/naprender/src/bufferbindinginstance.cpp
  system_modules/naprender/src/bufferbindinginstance.h
  system_modules/naprender/src/depthrendertarget.cpp
  system_modules/naprender/src/depthrendertarget.h
  system_modules/naprender/src/imagefromfile.cpp
  system_modules/naprender/src/imagefromfile.h
  system_modules/naprender/src/irendertarget.h
  system_modules/naprender/src/materialinstance.cpp
  system_modules/naprender/src/renderableglyph.cpp
  system_modules/naprender/src/renderbloomcomponent.cpp
  system_modules/naprender/src/renderservice.cpp
  system_modules/naprender/src/renderservice.h
  system_modules/naprender/src/rendertarget.cpp
  system_modules/naprender/src/rendertarget.h
  system_modules/naprender/src/rendertexture2d.cpp
  system_modules/naprender/src/rendertexture2d.h
  system_modules/naprender/src/rendertexturecube.cpp
  system_modules/naprender/src/rendertexturecube.h
  system_modules/naprender/src/renderutils.cpp
  system_modules/naprender/src/renderutils.h
  system_modules/naprender/src/renderwindow.cpp
  system_modules/naprender/src/renderwindow.h
  system_modules/naprender/src/shader.cpp
  system_modules/naprender/src/snapshot.cpp
  system_modules/naprender/src/snapshotrendertarget.cpp
  system_modules/naprender/src/snapshotrendertarget.h
  system_modules/naprender/src/structfillpolicy.cpp
  system_modules/naprender/src/texture.cpp
  system_modules/naprender/src/texture.h
  system_modules/naprender/src/texturelink.h
  system_modules/naprender/src/textureutils.cpp
  system_modules/naprender/src/textureutils.h
  system_modules/naprenderadvanced/src/cubedepthrendertarget.cpp
  system_modules/naprenderadvanced/src/cubedepthrendertarget.h
  system_modules/naprenderadvanced/src/cubemapfromfile.cpp
  system_modules/naprenderadvanced/src/cubemapfromfile.h
  system_modules/naprenderadvanced/src/cuberendertarget.cpp
  system_modules/naprenderadvanced/src/cuberendertarget.h
  system_modules/naprenderadvanced/src/renderadvancedservice.cpp
  system_modules/naprenderadvanced/src/renderfrustumcomponent.cpp
  system_modules/napvideo/src/videoplayer.cpp
Labels: enhancement, rendering
